version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

  api:
    build: ./api
    ports:
      - "5075:5075"
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ConnectionStrings__DefaultConnectionString=Server=mssql,1433;Database=WarehouseManagementSystem;User Id=sa;Password=Str0ngP@ssw0rd!2026;Encrypt=False;TrustServerCertificate=True

    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Str0ngP@ssw0rd!2026"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"