name: WMS CI/CD

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Repo clone
      - name: Checkout
        uses: actions/checkout@v3


      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push API
        run: |
          docker build -t akodevv/wms-api:${{ github.sha }} ./api
          docker tag akodevv/wms-api:${{ github.sha }} akodevv/wms-api:latest
          docker push akodevv/wms-api:${{ github.sha }}
          docker push akodevv/wms-api:latest


      - name: Build & Push Frontend
        run: |
          docker build --no-cache -t akodevv/wms-frontend:${{ github.sha }} ./frontend
          docker tag akodevv/wms-frontend:${{ github.sha }} akodevv/wms-frontend:latest
          docker push akodevv/wms-frontend:${{ github.sha }}
          docker push akodevv/wms-frontend:latest


      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ec2-user/WMS-Docker || git clone https://github.com/Ako0010/WMS-Docker.git
            
            cd /home/ec2-user/WMS-Docker
            
            git fetch --all
            git reset --hard origin/master

            docker compose pull frontend api

            docker compose down
            
            docker compose up -d --force-recreate

            docker image prune -f